# Generated by Django 6.0.6 on 2026-07-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('generic_name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('dosage_form', models.CharField(blank=True, max_length=50, null=True)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('min_stock_level', models.IntegerField(default=20)),
                ('max_stock_level', models.IntegerField(default=500)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='inventory_m_name_7f2fd2_idx'), models.Index(fields=['generic_name'], name='inventory_m_generic_acb93c_idx')],
            },
        ),
    ]
