# Generated by Django 6.0.6 on 2026-07-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('inventory', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('dosage_instructions', models.CharField(max_length=255)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.medicine')),
            ],
            options={
                'db_table': 'inventory_prescriptionitem',
            },
        ),
    ]
