# Generated by Django 6.0.6 on 2026-07-06 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_prescriptionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('inventory_batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.inventory')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.prescriptionitem')),
            ],
            options={
                'db_table': 'inventory_prescriptionallocation',
            },
        ),
    ]
